
import Script from 'next/script'
import './globals.css'

export const metadata = {
  title: 'Maps',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>{children}</body>

    </html>
  )
}
